//对象数组
import com.cad
var cad = com.cad();
cad.Visible = true;  

var patternName = "ANSI31";//填充图案的名称
var patternType = 0 ;// 填充类型

//在模型空间中添加填充图案对象（Hatch）
var hatchObj = cad.ActiveDocument.ModelSpace.AddHatch(patternType, patternName, true);

//定义圆心和半径
var centerPoint = {0;0;0};
var radius = 1;

//创建圆对象
var circle = cad.ActiveDocument.ModelSpace.AddCircle(centerPoint, radius);

/*
如果数组成员为普通 COM 对象（IDispatch 对象），在 COM 接口中自动转换为 VT_DISPATCH 类型 SafeArray。
细节请参考「aardio 范例 / COM 组件 / 进阶提示 / 类型转换规则」
*/
var outerLoop = { circle };

//添加一个圆作为填充图案的外循环边界
hatchObj.AppendOuterLoop (  outerLoop );

//计算并更新填充图案
hatchObj.Evaluate();

//重新生成视图
cad.ActiveDocument.Regen(cad.acActiveViewport);